openapi: 3.0.0
info:
  title: Todo API
  description: REST API for Todo App
  version: 1.0.0
  contact:
    name: Peter John R. Rueca
    url: https://linkedin.com/in/peterrueca
servers:
  - url: http://localhost:{port}
    variables:
      port:
        enum:
          - '3000'
          - '8000'
          - '8080'
        default: '3000'
tags:
  - name: CRUD
    description: Basic database operations
paths:
  /api/todo:
      post:
        description: Add todo item
        tags:
          - CRUD
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  todo:
                    type: string
        parameters:
          - in: header
            name: X-API-Key
            required: true
            schema:
              type: string
            description: API key for authentication
        responses:
          200:
            description: Success
          400:
            description: Bad request
          500:
            description: Internal server error
          default:
            description: Success
      get:
        description: Get all todo items
        tags:
          - CRUD
        parameters:
          - in: header
            name: X-API-Key
            required: true
            schema:
              type: string
            description: API key for authentication
        responses:
          200:
            description: Success
          400:
            description: Bad request
          500:
            description: Internal server error
          default:
            description: Success
  /api/todo/{id}:
    get:
      description: Get todo item
      tags:
        - CRUD
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: header
          name: X-API-Key
          required: true
          schema:
            type: string
          description: API key for authentication
      responses:
        200:
          description: Success
        404:
          description: Data not found
        400:
          description: Bad request
        500:
          description: Internal server error
        default:
          description: Success
    put:
      description: Update todo item
      tags:
        - CRUD
      parameters:
        - in: header
          name: X-API-Key
          required: true
          schema:
            type: string
          description: API key for authentication
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                todo:
                  type: string
                done:
                  type: boolean
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
        default:
          description: Success
    delete:
      description: Delete todo item
      tags:
        - CRUD
      parameters:
        - in: header
          name: X-API-Key
          required: true
          schema:
            type: string
          description: API key for authentication
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
        400:
          description: Bad request
        500:
          description: Internal server error
        default:
          description: Success