version: "3"
services:
  app:
    build: .
    image: todo-api
    container_name: todo-api
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql
    container_name: todo-db
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306